crud_operations/crud_app/urls.py
from django.urls import path
from .views import *
from .views import delete_todo
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("", register_page, name="register_page"),
    path("index", index, name="index"),
    # path("login", login_page, name="login_page"),
    path("login/", LoginView.as_view(), name="login_page"),
    path("logout", logout_view, name="logout"),
    path("ced_todo", ced_todo, name="ced_todo"),
    path("my_blog", my_blog, name="my_blog"),
    path("delete_todo/<int:id>/", delete_todo, name="delete_todo"),
    path("edit_todo/<int:id>/", edit_todo, name="edit_todo"),
    path("verify_otp", verify_otp, name="verify_otp"),
    path('resend_otp/', resend_otp, name='resend_otp'),
    path('view_todo/<int:id>/', view_todo, name='view_todo'),
    path("user_profile", user_profile, name="user_profile"),
    path("edit_profile", edit_profile, name="edit_profile"),
    path("premium", premium, name="premium"),
    path('forgot_password/', forgotpasswordpage, name='forgot_password'),
    path('change_password/<str:token>/', changepassword, name='change_password'),
    path('todo/<int:id>/like/', like_todo, name='like_todo'),
    path('todo/<int:id>/comment/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud_operations/crud_operations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("crud_app.urls")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crud_operations/crud_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from .manager import CustomUserManager
import re
from django.core.validators import RegexValidator

# Create your models here.
password_regex = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d).{8,}$'
password_validator = RegexValidator(
    regex=password_regex,
    message='Password must contain at least 8 characters, one uppercase letter, one lowercase letter, and one number',
)
email_regex =  r'^(?=.*\d).{8,}$'
email_validator = RegexValidator(
    regex=email_regex,
    message = 'Email must contain at least 8 characters, one uppercase letter, and one number',
)

class CustomUser(AbstractUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=254, unique=True, validators=[email_validator])
    password = models.CharField(max_length=128, validators=[password_validator])
    phone = models.CharField(max_length=15, null=True, blank=True)
    gender = models.CharField(max_length=10, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    bio = models.CharField(max_length=500, null=True, blank=True)
    forgot_password_token = models.CharField(max_length=100, null=True, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
      return self.email

class ToDo(models.Model):
  user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
  title = models.CharField(max_length=100)
  description = models.TextField()
  created_at = models.DateField(default=timezone.now)
  updated_at = models.DateField(default=timezone.now)
  blog_image = models.ImageField(upload_to='todo_images/', blank=True, null=True)

  def __str__(self):
    return self.title

class Profile(models.Model):
  user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
  image = models.ImageField(default='default.jpg', upload_to='profile_pics/')

  def __str__(self):
    return f'{self.user.email} Profile'
  
class blog_image(models.Model):
  user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
  blog_image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
  
  def __str__(self):
    return self.blog_image
  
class Like(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    todo = models.ForeignKey(ToDo, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'todo')

class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    todo = models.ForeignKey(ToDo, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.todo.title}'

crud_operations/crud_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password, check_password
from .models import ToDo, CustomUser, Profile, Like, Comment
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from .utils import send_email
from django.core.mail import send_mail
from django.conf import settings
import random
from django.utils import timezone
from .helpers import send_forget_password_email
import uuid
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.urls import reverse
from rest_framework import status
from rest_framework.generics import GenericAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken
from . import serializers
from rest_framework import generics
from .serializers import UserLoginSerializer
import re

# Create your views here.
email_regex =  r'^(?=.*\d).{8,}$'
email_validator = RegexValidator(
    regex=email_regex,
    message = 'Email must contain at least 8 characters, one uppercase letter, and one number',
)
password_regex = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d).{8,}$'
password_validator = RegexValidator(
    regex=password_regex,
    message = 'Password must contain at least 8 characters, one uppercase letter, one lowercase letter, and one number',
)

def generate_otp():
    return random.randint(1000,9999)
    
def send_email(email, first_name, otp):
    subject = 'ToDo App'
    message = f'Hi {first_name}, Your OTP is {otp}'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message, email_from, recipient_list)


@csrf_protect
@never_cache
def register_page(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if not re.match(r'^[A-Za-z]+$', first_name):
            error = "First name should only contain letters and no spaces or special characters."
            return render(request, 'register.html', {'error': error})

        # Validate last name
        if not re.match(r'^[A-Za-z]+$', last_name):
            error = "Last name should only contain letters and no spaces or special characters."
            return render(request, 'register.html', {'error': error})

        try:
            email_validator(email)
        except ValidationError as e:
            error = "Email must contain at least 8 characters, one uppercase letter, and one number"
            return render(request, 'register.html', {'error': error})

        try:
            password_validator(password)
        except ValidationError as e:
            error = "Password must contain at least 8 characters, one uppercase letter, one lowercase letter, and one number"
            return render(request, 'register.html', {'error': error})
        
        if password != confirm_password:
            error = "Password and confirm password must be same."
            return render(request, 'register.html', {'error': error})
        
        if CustomUser.objects.filter(email=email).exists():
            error = "Email already exists"
            return render(request, 'register.html', {'error': error})
        
        otp = generate_otp()
        send_email(email, first_name, otp)
        request.session['otp'] = otp
        request.session['otp_time'] = timezone.now().timestamp()
        # request.session['username'] = username
        request.session['first_name'] = first_name
        request.session['last_name'] = last_name
        request.session['email'] = email
        request.session['password'] = password
        # request.session['phone'] = phone

        return redirect('verify_otp')
    return render(request, 'register.html')

@csrf_protect
def verify_otp(request):
    if request.method == "POST":
        user_otp = request.POST.get('otp')
        session_otp = request.session.get('otp')
        otp_time = request.session.get('otp_time')
        current_time = timezone.now().timestamp()
        # print(user_otp, type(user_otp), 44444444)
        # print(session_otp, type(session_otp), 8888888888)

        if current_time - otp_time > 30:
            error = "OTP has expired. Please request a new one."
            return render(request, 'verify_otp.html', {'error': error})
        
        if int(user_otp) == session_otp:
            first_name = request.session.get('first_name')
            last_name = request.session.get('last_name')
            email = request.session.get('email')
            password = request.session.get('password')

            user = CustomUser.objects.create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=make_password(password),
            )

            del request.session['otp']
            del request.session['otp_time']
            del request.session['first_name']
            del request.session['last_name']
            del request.session['email']
            del request.session['password']
            return redirect('login_page')
        else:
            return HttpResponse("Invalid OTP", status=404)

    return render(request, 'verify_otp.html')

class LoginView(generics.GenericAPIView):
    serializer_class = UserLoginSerializer
    permission_classes = (AllowAny,)

    def post(self, request):
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            user = serializer.validated_data['user']
            login(request, user)
            return redirect('index')  # Redirect to the dashboard page after login
        else:
            # If validation fails, render the login page with the error message
            return render(request, 'login.html', {'errors': serializer.errors, 'form': serializer.data})

    def get(self, request):
        return render(request, 'login.html')

@login_required
def ced_todo(request):
    if request.method == 'POST':
        u = request.user
        title = request.POST['title']
        description = request.POST['description']
        blog_image = request.FILES.get('blog_image')

        if blog_image:
            print("Received image:", blog_image.name)

        todo = ToDo.objects.create(title=title, description=description, user=u, blog_image=blog_image)

        todo.save()
        return redirect('index')
    return render(request, 'ced_todoo.html')

@csrf_protect
@never_cache
@login_required
def index(request):
    u = request.user

    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        blog_image = request.FILES.get('blog_image')

        todo = ToDo.objects.create(title=title, description=description, user=u, blog_image=blog_image)
        todo.save()
        return redirect('index')

    # Fetch todos from all users (or modify the filter as needed)
    todos = ToDo.objects.filter(user=u).all()  # Current user's todos
    other_users_todos = ToDo.objects.exclude(user=u)  # Todos from other users
    all_todos = todos.union(other_users_todos)
    return render(request, 'dashboard.html', {'todos': all_todos})
@never_cache
@login_required
def logout_view(request):
    logout(request)
    return redirect('login_page')

@login_required
def edit_todo(request, id):
    todo = ToDo.objects.get(id=id)
    print(todo.title, "fdghjkl")
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        blog_image = request.FILES.get('blog_image')

        todo.title = title
        todo.description = description
        if blog_image:
            todo.blog_image = blog_image
            
        todo.updated_at = datetime.now()
        todo.save()
        return redirect('index')
    return render(request, 'edit_todo.html', {'todo': todo})

@login_required
def delete_todo(request, id):
    todo = get_object_or_404(ToDo, id=id)
    todo.delete()
    return redirect('my_blog')

def resend_otp(request):
    otp = generate_otp()
    send_email(request.session.get('email'), request.session.get('first_name'), otp)
    request.session['otp'] = otp
    request.session['otp_time'] = timezone.now().timestamp()
    return redirect('verify_otp')

def my_blog(request):
    user = request.user
    todos = ToDo.objects.filter(user=user)
    return render(request, 'my_blog.html', {'todos': todos})

@login_required
def view_todo(request, id):
    todo = ToDo.objects.get(id=id)
    likes = Like.objects.filter(todo=todo)
    comments = Comment.objects.filter(todo=todo)
    return render(request, 'view_todo.html', {'todo': todo, 'comments': comments, 'likes': likes})


@login_required
def user_profile(request):
    return render(request, 'user_profile.html')

def profile(request):
    return render(request, 'profile.html')

def blog_image(request):
    return render(request, 'blog_image.html')

@login_required
def edit_profile(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone = request.POST.get('phone')
        gender = request.POST.get('gender')
        bio = request.POST.get('bio')
        dob = request.POST.get('dob')
        profile_image = request.FILES.get('profile_image')

crud_operations/crud_app/templates/blog_image.html
{% extends "view_todo.html" %}

{% block content %}
    <div class="blog_image">
      <h2>{{ blog.title }}</h2>
      <img src="{{ blog.image.url }}" alt="image" style="width: 100%; height: 100%;">
    </div>
{% endblock %}

crud_operations/crud_app/templates/ced_todoo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Create Blog</title>
    <link rel="stylesheet" href="{% static 'style2.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="main">
        <div class="container">
            <h2>Create Blog</h2>
            <form method="POST" action="" enctype='multipart/form-data'>
                {% csrf_token %}
                <label for="title">Title:</label>
                <input type="text" name="title" id="title" required><br>
                <label for="description">Description:</label>
                <textarea name="description" id="description" required></textarea><br>
                <label for="image"> Blog Image:</label>
                <input type="file" id="blog_image" name="blog_image" accept="image/*"><br>
                <div class="button-group">
                    <button type="submit">Create</button>
                    <a href="{% url 'index' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

crud_operations/crud_app/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'style1.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    
    <main class="container">
        <section class="create-blog">
            <h2>Create blog</h2>
            <form method="POST" action="" enctype='multipart/form-data'>
                {% csrf_token %}
                <label for="title">Title:</label>
                <input type="text" id="title" name="title" required>
                
                <label for="description">Description:</label>
                <textarea id="description" name="description" required></textarea>
                
                <label for="image"> Blog Image:</label>
                <input type="file" id="blog_image" name="blog_image" accept="image/*">
                
                <button type="submit">Create</button>
            </form>
        </section>
        
        <section class="blog-list">
            {% for todo in todos reversed %}  
            <a class="blog-card" href="{% url 'view_todo' todo.id %}">
                <div class="blog-image">
                    {% if todo.blog_image %}
                        <img src="{{ todo.blog_image.url }}" alt="{{ todo.title }}" class="blog-image" style="width: 150px; height: 150px; border-radius: 10%;">
                    {% endif %}
                </div>
                <div class="blog-content">
                    <h3>Title: {{ todo.title }}</h3>
                    <p>Description: {{ todo.description|truncatewords:10 }}</p>
                    <p>Author: {{ todo.user.first_name }} {{ todo.user.last_name }}</p>
                    <div class="blog-actions">
                        <form action="{% url 'like_todo' todo.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">
                                Like <i class="fa-solid fa-thumbs-up"></i> ({{ todo.like_set.count }})
                            </button>
                        </form>
                        <form action="{% url 'view_todo' todo.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">
                                Comments ({{ todo.comments.count }})
                            </button>
                        </form>
                    </div>
                </div>
                <div class="blog-meta">
                    <span>Created at: {{ todo.created_at }}</span>
                    <span>Updated at: {{ todo.updated_at }}</span>
                </div>
            </a>
            {% endfor %}
        </section>
    </main>
</body>
</html>

crud_operations/crud_app/templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>EDIT PROFILE</title>
    <link rel="stylesheet" href="{% static "edit_profile.css" %}">
</head>
<body>
  {% include 'navbar.html' %}
  <div class="main">
    <div class="edit">
      <h1>Edit Profile</h1>
      <form method="post" action="" enctype='multipart/form-data'>
          {% csrf_token %}
          <label for="fname">First name:</label>
          <input type="text" id="fname" name="first_name" value="{{ user.first_name }}" required>

          <label for="lname">Last name:</label>
          <input type="text" id="lname" name="last_name" value="{{ user.last_name }}" required>

          <label for="phone"> Phone No. </label>
          <input type="text" name="phone" value="{{ user.phone }}" required>

          <label for="image">Profile Picture:</label>
          <input type="file" id="profile_image" name="profile_image" accept="image/*">

          <label for="gender">Gender</label>
          <div class="radio-container">
          <div>
              <input type="radio" id="male" name="gender" value="male" {% if user.gender == 'male' %}checked{% endif %}>
              <label for="male">Male</label>
          </div>
          <div>
              <input type="radio" id="female" name="gender" value="female" {% if user.gender == 'female' %}checked{% endif %}>
              <label for="female">Female</label>
          </div>
        </div>

          <label for="dob">Date of Birth</label>
          <input type="date" id="dob" name="dob" value="{{ user.dob }}" required> 

          <label for="bio">Bio</label>
          <textarea id="bio" name="bio" rows="4" cols="50" required>{{ user.bio }}</textarea>

          <div class="button-container">
          <a href="{% url 'user_profile' %}" class="back-button">Back</a>
          <button type="submit">Save</button>
          </div>
      </form>
    </div>
  </div>
</body>
</html>

crud_operations/crud_app/templates/edit_todo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Blog</title>
    <link rel="stylesheet" href="{% static 'style2.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="main">
        <div class="container">
            <h2>Edit Blog</h2>
            <form method="POST" action="{% url 'edit_todo' todo.id %}" enctype='multipart/form-data'>
                {% csrf_token %}
                <label for="title">Title:</label>
                <input type="text" name="title" id="title" value="{{ todo.title }}" required><br>
                <label for="description">Description:</label>
                <textarea name="description" id="description" required>{{ todo.description }}</textarea><br>
                <label for="image"> Blog Image:</label>
                <input type="file" id="blog_image" name="blog_image" accept="image/*"><br>
                <div class="button-group">
                    <button type="submit">Save</button>
                    <a href="{% url 'my_blog' %}" >Cancel</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

crud_operations/crud_app/templates/forgotpassword.html
{% load static %}
<html>
  <head>
    <title>Forgot Password</title>
    {% comment %} <link rel="stylesheet" href="{% static 'style2.css' %}"> {% endcomment %}
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        background-image: url('https://img.freepik.com/free-photo/blue-toned-paper-sheets-with-copy-space_23-2148320450.jpg?t=st=1718175613~exp=1718179213~hmac=f1f6678aa86f2d2dfa5b4a538eaa7fae9676603f39b604fc077651ef4af75b4e&w=1060');
        background-size: cover;
        background-repeat: no-repeat;
      }
      .container {
        width: 30%;
        margin: 0 auto;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 40px rgba(0, 0, 0, 0.2);
        margin-top: 200px;
      }
      h2 {
        text-align: center;
        margin-bottom: 20px;
      }
      form {
        display: flex;
        flex-direction: column;
      }
      label {
        margin-bottom: 5px;
      }
      input {
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
      }
      .button-group {
        display: flex;
        justify-content: center;
        gap: 50px;
      }
      button {
        padding: 10px 20px;
        background-color: #3498db;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 10px;
      }
      button:hover {
        background-color: #2980b9;
        transition-duration: 0.3s;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>Forgot Password</h2>
      {% if error %}
        <p style="color: red;">{{ error }}</p>
      {% endif %}
      <form method="POST" action="">
        {% csrf_token %}
        <label for="email">Email:</label>
        <input type="email" name="email" id="email" placeholder="Enter your email id" required>
        <div class="button-group">
          <button type="button" onclick="window.location.href = '{% url "login_page" %}'">Back</button>
          <button type="submit">Request mail</button>
        </div>
      </form>
    </div>
  </body>
</html>

crud_operations/crud_app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>LOGIN PAGE</title>
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'stylel.css' %}">
</head>
<body>
<div class="main">
</a>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <label for="email">Email :</label>
        <input type="text" id="email" name="email" placeholder="Enter your email id" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" placeholder="Enter your password" required>
        {% if errors %}
            <div class="error-messages">
                <ul>
                    {% for field, messages in errors.items %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <button type="submit">Submit</button>
    </form>
    <p>Don't have an account? <a href= "{% url "register_page" %}" style="text-decoration: none;">Sign Up</a></p>
    <a href= "{% url 'forgot_password' %}" style="text-decoration: none;">Forgot Password ?</a>
</div>
</body>
</html>

crud_operations/crud_app/templates/premium.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Premium Access</title>
    <link rel="stylesheet" href="{% static "premium.css" %}">
  </head>
  <body>
    <h1>Premium Access</h1>
    <p>Upgrade to premium to get access to more features</p>
    <div class="premium-features">
      <ul>
        <li>Ad-free Experience</li>
        <li>Access to more blogs</li>
        <li>Offline Access</li>
        <li>100 personal blogs</li>
      </ul>
    </div>
    <div class="button-group">
      <a href="{% url 'index' %}">Cancel</a>
      <button>Upgrade to Premium</button>
    </div>
  </body>
</html>

crud_operations/crud_app/templates/profile.html
{% extends "dashboard.html" %}

{% block content %}
    <div class="profile">
      <h2>{{ user.username }}</h2>
      <img src="{{ user.profile_image.url }}" alt="{{ user.username }}'s profile picture" style="width: 150px; height: 150px; border-radius: 50%;">
    </div>
{% endblock %}

crud_operations/crud_app/templates/view_todo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ todo.title }}</title>
    <link rel="stylesheet" href="{% static 'view_todo.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container1">
        <ul>
            <li>
                <div class="header">
                    {% if todo.blog_image %}
                        <img src="{{ todo.blog_image.url }}" alt="{{ todo.title }}" class="blog-image">
                    {% endif %}
                    <div class="header-content">
                        <h2>{{ todo.title }}</h2>
                        <h3>By: {{ todo.user.first_name }} {{ todo.user.last_name }}</h3>
                    </div>
                </div>
                <span class="description">Description: {{ todo.description }}</span>
                <div class="timestamps">
                    <span class="timestamp created_at">Created At: {{ todo.created_at }}</span>
                    <span class="timestamp updated_at">Updated At: {{ todo.updated_at }}</span>
                </div>

                <div class="interaction-container">
                    <form action="{% url 'like_todo' todo.id %}" method="post" class="like-form">
                        {% csrf_token %}
                        <button type="submit" class="like-button">
                            Like <i class="fa-solid fa-thumbs-up"></i> ({{ todo.like_set.count }})
                        </button>
                    </form>
                    <form action="{% url 'add_comment' todo.id %}" method="post" class="add-comment-form">
                        {% csrf_token %}
                        <textarea name="content" required placeholder="Add a comment..."></textarea>
                        <button type="submit" class="add-comment-button">Send <i class="fa-solid fa-paper-plane"></i></button>
                    </form>
                </div>
                
                <div class="comments-section">
                    <h3>Comments <i class="fa-solid fa-comment"></i></h3>
                    <ul>
                        {% for comment in todo.comments.all reversed %}
                            <li>
                                {{ comment.user.first_name }}: {{ comment.content }} ({{ comment.created_at }})
                                {% if comment.user == request.user %}
                                <form action="{% url 'delete_comment' comment.id %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="delete-button"><i class="fa-solid fa-trash"></i></button>
                                </form>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</body>
</html>